"""Add ON DELETE CASCADE to borrowed_books foreign key

Revision ID: 7f01d603f0a1
Revises: 771b1440a256
Create Date: 2024-11-28 15:37:58.036636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f01d603f0a1'
down_revision = '771b1440a256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the index on 'books.title'
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('idx_books_title')

    # Alter the foreign key in 'borrowed_books' to add 'ON DELETE CASCADE'
    with op.batch_alter_table('borrowed_books', schema=None) as batch_op:
        batch_op.drop_constraint('borrowed_books_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_borrowed_books_borrowed_by_user_users',  # New FK name
            'users',  # Referenced table
            ['borrowed_by_user'],  # Local column
            ['username'],  # Referenced column
            ondelete='CASCADE'  # Adding CASCADE behavior
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert the foreign key to remove 'ON DELETE CASCADE'
    with op.batch_alter_table('borrowed_books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_borrowed_books_borrowed_by_user_users', type_='foreignkey')
        batch_op.create_foreign_key(
            'borrowed_books_ibfk_2',  # Original FK name
            'users',  # Referenced table
            ['borrowed_by_user'],  # Local column
            ['username']  # Referenced column
        )

    # Recreate the index on 'books.title'
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('idx_books_title', ['title'], unique=True)

    # ### end Alembic commands ###
