"""Add cascading delete to borrowed_books

Revision ID: fa3a409f4f95
Revises: 7f01d603f0a1
Create Date: 2024-11-28 16:23:06.335373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3a409f4f95'
down_revision = '7f01d603f0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('idx_books_title')

    with op.batch_alter_table('borrowed_books', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['borrowed_by_user'], ['username'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('idx_books_title', ['title'], unique=True)

    # ### end Alembic commands ###
